# Generated by Django 3.0.6 on 2020-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('ethereum_address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
