# Generated by Django 3.0.6 on 2020-05-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplasma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='three_box_profile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
