# Generated by Django 3.0.6 on 2020-05-11 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dplasma', '0003_auto_20200510_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('ethereum_address', models.CharField(max_length=255)),
                ('three_box_profile', models.CharField(max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospital', to='dplasma.Hospital')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
