# Generated by Django 3.0.6 on 2020-05-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dplasma', '0006_donor_hematologist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='ethereum_address',
        ),
    ]
