# Generated by Django 3.0.6 on 2020-05-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplasma', '0008_auto_20200511_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(default='New York', max_length=255),
        ),
    ]
