# Generated by Django 3.0.6 on 2020-05-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplasma', '0009_auto_20200511_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='ethereum_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
